#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Oct 28 01:20:56 PDT 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto db09b55c78fe40d9a37bf01f3901b1a1 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_uart_rx_behav xil_defaultlib.tb_uart_rx -log elaborate.log"
xelab -wto db09b55c78fe40d9a37bf01f3901b1a1 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_uart_rx_behav xil_defaultlib.tb_uart_rx -log elaborate.log

