#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Nov 20 19:21:15 PST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 3cce6d4ad95443a8ad3224579f05fce1 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_uart_top_controller_behav xil_defaultlib.tb_uart_top_controller -log elaborate.log"
xelab -wto 3cce6d4ad95443a8ad3224579f05fce1 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_uart_top_controller_behav xil_defaultlib.tb_uart_top_controller -log elaborate.log

