webtalk_init -webtalk_dir /home/aaronnanas/vivado_projects/ece524_final_proj/top_level_fsm_controller/top_level_fsm_controller.sim/sim_1/behav/xsim/xsim.dir/tb_top_fsm_controller_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Nov 28 00:12:52 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212015417_0_0_623" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5a660575-346a-4002-9507-2943d44cd536" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b80513a1080b47119a38e6a31eb57727" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "64" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2300.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.11_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "117324_KB" -context "xsim\\usage"
webtalk_transmit -clientid 743286743 -regid "212015417_0_0_623" -xml /home/aaronnanas/vivado_projects/ece524_final_proj/top_level_fsm_controller/top_level_fsm_controller.sim/sim_1/behav/xsim/xsim.dir/tb_top_fsm_controller_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/aaronnanas/vivado_projects/ece524_final_proj/top_level_fsm_controller/top_level_fsm_controller.sim/sim_1/behav/xsim/xsim.dir/tb_top_fsm_controller_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/aaronnanas/vivado_projects/ece524_final_proj/top_level_fsm_controller/top_level_fsm_controller.sim/sim_1/behav/xsim/xsim.dir/tb_top_fsm_controller_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
