#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Nov 27 23:34:52 PST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto b80513a1080b47119a38e6a31eb57727 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_top_fsm_controller_behav xil_defaultlib.tb_top_fsm_controller -log elaborate.log"
xelab -wto b80513a1080b47119a38e6a31eb57727 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_top_fsm_controller_behav xil_defaultlib.tb_top_fsm_controller -log elaborate.log

