# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/aaronnanas/vivado_projects/ece524_final_proj/telemetry_bot_top/telemetry_bot_top.srcs/sources_1/bd/telemetry_bot/ip/telemetry_bot_processing_system7_0_0/telemetry_bot_processing_system7_0_0.xci
# IP: The module: 'telemetry_bot_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aaronnanas/vivado_projects/ece524_final_proj/telemetry_bot_top/telemetry_bot_top.gen/sources_1/bd/telemetry_bot/ip/telemetry_bot_processing_system7_0_0/telemetry_bot_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'telemetry_bot_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/aaronnanas/vivado_projects/ece524_final_proj/telemetry_bot_top/telemetry_bot_top.srcs/sources_1/bd/telemetry_bot/ip/telemetry_bot_processing_system7_0_0/telemetry_bot_processing_system7_0_0.xci
# IP: The module: 'telemetry_bot_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aaronnanas/vivado_projects/ece524_final_proj/telemetry_bot_top/telemetry_bot_top.gen/sources_1/bd/telemetry_bot/ip/telemetry_bot_processing_system7_0_0/telemetry_bot_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'telemetry_bot_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
