#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Nov 21 10:29:16 PST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 6f27abab0b4749468af8d63ca3fc60d6 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_inferred_bram_for_image_behav xil_defaultlib.tb_inferred_bram_for_image -log elaborate.log"
xelab -wto 6f27abab0b4749468af8d63ca3fc60d6 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_inferred_bram_for_image_behav xil_defaultlib.tb_inferred_bram_for_image -log elaborate.log

