#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Nov 21 10:29:17 PST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_inferred_bram_for_image_behav -key {Behavioral:sim_1:Functional:tb_inferred_bram_for_image} -tclbatch tb_inferred_bram_for_image.tcl -log simulate.log"
xsim tb_inferred_bram_for_image_behav -key {Behavioral:sim_1:Functional:tb_inferred_bram_for_image} -tclbatch tb_inferred_bram_for_image.tcl -log simulate.log

