# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zybo_z720_constraints.xdc

# Block Designs: bd/telemetry_bot/telemetry_bot.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==telemetry_bot || ORIG_REF_NAME==telemetry_bot} -quiet] -quiet

# IP: bd/telemetry_bot/ip/telemetry_bot_processing_system7_0_0/telemetry_bot_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==telemetry_bot_processing_system7_0_0 || ORIG_REF_NAME==telemetry_bot_processing_system7_0_0} -quiet] -quiet

# IP: bd/telemetry_bot/ip/telemetry_bot_top_level_controller_0_0/telemetry_bot_top_level_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==telemetry_bot_top_level_controller_0_0 || ORIG_REF_NAME==telemetry_bot_top_level_controller_0_0} -quiet] -quiet

# XDC: /home/aaronnanas/vivado_projects/ece524_final_proj/telemetry_bot_top/telemetry_bot_top.gen/sources_1/bd/telemetry_bot/telemetry_bot_ooc.xdc
